### ISSUE TITLE
Division ambiguity

### ISSUE THREAD

**Issue by jaspajjr** [DomDuxbury/bitcoin-price-analysis#1]
Visualizer.py line 40, you do a division, without having first imported at the top of the script:
```
from __future__ import division
```
See for https://www.python.org/dev/peps/pep-0238/ for more info

**Comment by DomDuxbury** [comment]
Fixed! https://github.com/DomDuxbury/bitcoin-price-analysis/commit/28629c2f8cc0c02f18ed830573734a4b66511ab5
